[features]
seeds = false
[programs.devnet]
cz_story_commit = "2HV1ywovUQmKbVkadpBPpb9fSAE4sYfhpPxCUFg26FCp"

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "localnet"
wallet = "/home/simon/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
